changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - "**/*.{test,spec,stories,storybook}.{js,ts,jsx,tsx}"

enableTransparentWorkspaces: true

initFields:
  version: 0.0.0
  description: ""
  files:
    - dist
    - README.md
  license: MIT
  publishConfig:
    access: public
    registry: "https://registry.npmjs.org/"
  repository:
    directory: packages/<!-- name -->
    type": git
    url: "https://github.com/phinpho/simplecomponent.git"
  type: module
  types: dist/index.d.ts

initScope: simplecomponent

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.5.3.cjs
