name: Lint and Test

on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "canary"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run --filter "*" lint

      - name: Test
        run: bun run --filter "*" test
